In [6]:
import constraint
import importlib
import matplotlib.pyplot as plt
import numpy as np
import pickle
from multiprocessing import Pool, cpu_count

In [2]:
from utils.tree_search import Node, Queue, Stack
import shelfsolver

In [5]:
shelf = shelfsolver.ShelfGenerator().new_random_shelf(seed=3)
print(shelf)

[[ 0 31 24  0 34]
 [44 42 43  0  0]
 [ 0  0 13 23 33]
 [21 22 12 11  0]
 [ 0 41 32 14  0]]


## Task 2: Sort objects so that each row has all the unique colors and all the unique shapes once 

Constraints:
* All colors are different per row
* All shapes are different per row

In [ ]:
problem = constraint.Problem()

possible_values = [0,11,12,13,14,21,22,23,24,31,32,33,34,41,42,43,44]

# Define position in the shelf as variables 11 (upper left) to 55 (lower right)
for i in range(1, 6): # all rows
    problem.addVariables(range(i*10+1,i*10+6), possible_values) # all cols
    
