In [1]:
import importlib
import matplotlib.pyplot as plt
import numpy as np
import pickle
from multiprocessing import Pool, cpu_count

In [2]:
from utils.tree_search import Node, Queue, Stack, Tree
import shelfsolver

# Tasks

1. Sort object so that each row has only objects of one color

2a. Sort objects so that each row has all the unique colors and all the unique shapes once 

2b. Sort objects so that each column has all the unique colors and all the unique shapes once 

3a. Sort objects so that each row and column has each of the four colors once. ← this task can take longer and may have longer duration than preceding tasks 

3b. Sort objects so that each row and column has each of the four shapes once. ← this task can take longer and may have longer duration than preceding tasks 

## Task 1: One color per row

### Solve single shelf

In [43]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf()
base_ids = solver.assign_bases(shelf)
print(shelf)
print(base_ids)

[[32 22  0 13  0]
 [ 0  0  0 21 34]
 [41  0 23 24 33]
 [43 44 31 11 12]
 [14  0  0 42  0]]
{0: 4, 1: 3, 2: 2, 3: 1, 4: None}


In [44]:
result = solver.solve(shelf, base_ids)

In [14]:
result

(array([[ 0, 21, 23, 22, 24],
        [ 0,  0,  0,  0,  0],
        [ 0, 12, 14, 11, 13],
        [ 0, 34, 31, 33, 32],
        [ 0, 42, 44, 41, 43]]),
 10)

### Solve multiple shelves

In [ ]:
# Collect search depths
depths = []
#solver = ShelfSolver()

use_multiprocessing = False

def thread_job(shelf):
    base_ids = solver.assign_bases(shelf)
    results = solver.solve(shelf=shelf, base_ids=base_ids)
    return results

n_tries = 200
#shelves = [solver.new_random_shelf() for _ in range(n_tries)]  

if use_multiprocessing:
    pool = Pool(processes=cpu_count())
    collected_depths = pool.map(thread_job, shelves)
    pool.close()
    
else:
    depths = []
    for i in range(n_tries):
        solver = ShelfSolver()
        shelf = solver.new_random_shelf()
        base_ids = solver.assign_bases(shelf)
        results = solver.solve(shelf, base_ids)
        if results:
            depths.append(results[0])
        with open('collected_depths.pickle', 'wb') as handle:
            pickle.dump(collected_depths, handle, protocol=pickle.HIGHEST_PROTOCOL)

## Task 2: Every row should contain items of unique color and shape

In [233]:
importlib.reload(shelfsolver)

<module 'shelfsolver' from '/home/pscl/Development/Projects/shelf-solver/shelfsolver.py'>

In [227]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf()
print(shelf)

[[ 0  0  0  0  0]
 [23 31 12 24  0]
 [44 13 14  0  0]
 [43 33 42  0 32]
 [11 21 34 41 22]]


In [ ]:
results = solver.solve_unique_per_row_with_scores(shelf, verbose=1, search_type="stack", collect=True)

In [ ]:
solver = shelfsolver.ShelfSolver()
shelfgen = shelfsolver.ShelfGenerator()
depths = []
n_tries = 400
for i in range(n_tries):
    if i%50==0:
        print('\n\n== Step {} ==\n'.format(i))
    shelf = shelfgen.new_random_shelf()
    results = solver.solve_unique_per_row_with_scores(shelf, task=2, search_type="stack", collect=True)
    if results:
        depths.append(results)
        with open('collected_depths/task2_setd.pickle', 'wb') as handle:
            pickle.dump(depths, handle, protocol=pickle.HIGHEST_PROTOCOL)

## Task 3: Each row and each column has each of the four colors once.

In [94]:
importlib.reload(shelfsolver)

<module 'shelfsolver' from '/home/pscl/Development/Projects/shelf-solver/shelfsolver.py'>

In [105]:
lis = []
for coreID in range(8):
    for i in range(200):
        lis.append(coreID+i*10)
print(len(set(lis)))
print(len(lis))
lis

1600
1600


[0,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 210,
 220,
 230,
 240,
 250,
 260,
 270,
 280,
 290,
 300,
 310,
 320,
 330,
 340,
 350,
 360,
 370,
 380,
 390,
 400,
 410,
 420,
 430,
 440,
 450,
 460,
 470,
 480,
 490,
 500,
 510,
 520,
 530,
 540,
 550,
 560,
 570,
 580,
 590,
 600,
 610,
 620,
 630,
 640,
 650,
 660,
 670,
 680,
 690,
 700,
 710,
 720,
 730,
 740,
 750,
 760,
 770,
 780,
 790,
 800,
 810,
 820,
 830,
 840,
 850,
 860,
 870,
 880,
 890,
 900,
 910,
 920,
 930,
 940,
 950,
 960,
 970,
 980,
 990,
 1000,
 1010,
 1020,
 1030,
 1040,
 1050,
 1060,
 1070,
 1080,
 1090,
 1100,
 1110,
 1120,
 1130,
 1140,
 1150,
 1160,
 1170,
 1180,
 1190,
 1200,
 1210,
 1220,
 1230,
 1240,
 1250,
 1260,
 1270,
 1280,
 1290,
 1300,
 1310,
 1320,
 1330,
 1340,
 1350,
 1360,
 1370,
 1380,
 1390,
 1400,
 1410,
 1420,
 1430,
 1440,
 1450,
 1460,
 1470,
 1480,
 1490,
 1500,
 1510,
 1520,
 1530,
 1540,
 1550,
 1560,
 1570,
 1580

In [99]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf(seed=10**9)
print(shelf)

[[33 43  0  0  0]
 [21  0 12  0 13]
 [42  0 11 41 44]
 [ 0 34 32 31  0]
 [23 14 22  0 24]]


In [62]:
results = solver.solve_task(shelf, task=3, verbose=1, search_type="stack", collect=False)
results

Fatal: No solution found.: 10 | Length of tree: 890
Function 'solve_task' finished after 20.0046 seconds.


In [60]:
solver = shelfsolver.ShelfSolver()
shelfgen = shelfsolver.ShelfGenerator()
depths = []
n_tries = 600
for i in range(n_tries):
    if i%50==0:
        print('\n\n== Step {} =='.format(i))
        print('Successful runs so far:', len(depths))
        with open('collected_depths/task3.pickle', 'wb') as handle:
            pickle.dump(depths, handle, protocol=pickle.HIGHEST_PROTOCOL)
    shelf = shelfgen.new_random_shelf()
    results = solver.solve_task(shelf, task=3, search_type="stack", collect=True)
    if results:
        depths.append(results)



== Step 0 ==
Successful runs so far: 0
Fatal: No solution found.
Function 'solve_task' finished after 20.0054 seconds.
Function 'solve_task' finished after 9.6055 seconds.
Function 'solve_task' finished after 0.9113 seconds.
Function 'solve_task' finished after 10.1747 seconds.
Function 'solve_task' finished after 16.7226 seconds.
Function 'solve_task' finished after 20.0003 seconds.
Fatal: No solution found.
Function 'solve_task' finished after 20.0017 seconds.
Function 'solve_task' finished after 2.2878 seconds.
Function 'solve_task' finished after 4.1558 seconds.
Function 'solve_task' finished after 20.0063 seconds.
Function 'solve_task' finished after 20.0047 seconds.
Function 'solve_task' finished after 20.0040 seconds.
Fatal: No solution found.
Function 'solve_task' finished after 20.0022 seconds.
Fatal: No solution found.
Function 'solve_task' finished after 20.0036 seconds.
Fatal: No solution found.
Function 'solve_task' finished after 20.0017 seconds.
Function 'solve_task' f

KeyboardInterrupt: 